print ("enter the first item")
firstitem =input()
print("enter the firstitem price")
firstitemprice =input()

print ("enter the second item")
seconditem =input()
print("enter seconditem price")
seconditemprice = input()

print ("enter the third item")
thirditem =input()
print("enter thirditem price")
thirditemprice =input()
print("this are all the groceries my wife bought" + firstitem + ";"  + str(firstitemprice) + seconditem + ":" + str(seconditemprice) + "," + thirditem + ":" + str(thirditemprice))